package com.techmart.interceptor;

import com.techmart.ejb.PlatformMetricsRegistry;
import jakarta.ejb.EJB;
import jakarta.interceptor.AroundInvoke;
import jakarta.interceptor.InvocationContext;
import java.io.Serializable;

public class PerformanceInterceptor implements Serializable {
    private static final long serialVersionUID = 1L;

    @EJB
    private PlatformMetricsRegistry metricsRegistry;

    @AroundInvoke
    public Object intercept(InvocationContext context) throws Exception {
        long startTime = System.currentTimeMillis();
        String methodName = context.getMethod().getName();
        String className = context.getTarget().getClass().getSimpleName();
        
        // Clean up proxy names generated by the container (e.g. ShoppingCartSession$Proxy$_$_WeldSubclass)
        if (className.contains("$")) {
            className = className.substring(0, className.indexOf("$"));
        }
        
        String ejbType = "Stateless";
        if (className.equals("ShoppingCartSession")) {
            ejbType = "Stateful";
        } else if (className.equals("PlatformMetricsRegistry")) {
            ejbType = "Singleton";
        } else if (className.contains("MDB") || className.contains("MessageDriven")) {
            ejbType = "MessageDriven";
        }

        Object result = null;
        String status = "SUCCESS";
        try {
            result = context.proceed();
            return result;
        } catch (Exception e) {
            status = "FAILED";
            throw e;
        } finally {
            long duration = System.currentTimeMillis() - startTime;
            if (metricsRegistry != null) {
                metricsRegistry.recordBeanCall(className + "." + methodName, ejbType, duration, status);
            }
        }
    }
}
